/// Flutter icons EvaluationIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EvaluationIcons
///      fonts:
///       - asset: fonts/EvaluationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EvaluationIcons {
  EvaluationIcons._();

  static const _kFontFam = 'EvaluationIcons';
  static const _kFontPkg = null;

  static const IconData sad = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData darkness = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh_regular = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile_regular = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
