/// Flutter icons HatCowBoy
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HatCowBoy
///      fonts:
///       - asset: fonts/HatCowBoy.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HatCowBoy {
  HatCowBoy._();

  static const _kFontFam = 'HatCowBoy';
  static const _kFontPkg = null;

  static const IconData hatCowBoy = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hatCowBoyOutline = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
